### ISSUE TITLE
provide source maps

### ISSUE THREAD

**Issue by matthewberryman** [urbanriskmap/cognicity-cards#36]
https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
This would help debugging on prod.

**Comment by matthewberryman** [comment]
```
vendor-bundle.js:1 Warning: a promise was rejected with a non-error: [object Object]    at g (https://cards.riskmap.in/scripts/vendor-bundle.js:1:14093)    at r.e._warn (https://cards.riskmap.in/scripts/vendor-bundle.js:1:18678)    at r._rejectCallback (https://cards.riskmap.in/scripts/vendor-bundle.js:2:8909)    at a._reject (https://cards.riskmap.in/scripts/vendor-bundle.js:2:15405)    at a._promiseRejected (https://cards.riskmap.in/scripts/vendor-bundle.js:2:15718)    at r._settlePromise (https://cards.riskmap.in/scripts/vendor-bundle.js:2:10433)    at r._settlePromise0 (https://cards.riskmap.in/scripts/vendor-bundle.js:2:11007)    at r._settlePromises (https://cards.riskmap.in/scripts/vendor-bundle.js:2:12226)    at i._drainQueue (https://cards.riskmap.in/scripts/vendor-bundle.js:1:6418)    at i._drainQueues (https://cards.riskmap.in/scripts/vendor-bundle.js:1:6479)    at drainQueues (https://cards.riskmap.in/scripts/vendor-bundle.js:1:4600)
j @ vendor-bundle.js:1
k @ vendor-bundle.js:1
g @ vendor-bundle.js:1
e._warn @ vendor-bundle.js:1
r._rejectCallback @ vendor-bundle.js:2
a._reject @ vendor-bundle.js:2
a._promiseRejected @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
t.importViewModelResource @ vendor-bundle.js:11
t.ensureViewModel @ vendor-bundle.js:12
e.loadRoute @ vendor-bundle.js:13
O @ vendor-bundle.js:9
A @ vendor-bundle.js:9
(anonymous) @ vendor-bundle.js:9
E @ vendor-bundle.js:9
t.run @ vendor-bundle.js:9
e @ vendor-bundle.js:9
o @ vendor-bundle.js:9
b @ vendor-bundle.js:9
t.run @ vendor-bundle.js:9
e @ vendor-bundle.js:9
(anonymous) @ vendor-bundle.js:9
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u._import @ vendor-bundle.js:7
e.loadText @ vendor-bundle.js:7
t.load @ vendor-bundle.js:13
t.load @ vendor-bundle.js:11
t.load @ vendor-bundle.js:11
(anonymous) @ vendor-bundle.js:11
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
a._resolve @ vendor-bundle.js:2
a._promiseFulfilled @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
o @ vendor-bundle.js:1
c.hasDevTools.i.invoke @ vendor-bundle.js:1
r._then @ vendor-bundle.js:2
r.then @ vendor-bundle.js:2
load @ vendor-bundle.js:7
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
u @ vendor-bundle.js:2
callPlugin @ vendor-bundle.js:3
fetch @ vendor-bundle.js:2
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
each @ vendor-bundle.js:2
emit @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
callPlugin @ vendor-bundle.js:3
fetch @ vendor-bundle.js:2
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
each @ vendor-bundle.js:2
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
e.loadAllModules @ vendor-bundle.js:7
t.importViewResources @ vendor-bundle.js:11
t.loadTemplateResources @ vendor-bundle.js:11
(anonymous) @ vendor-bundle.js:11
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u._import @ vendor-bundle.js:7
e.loadText @ vendor-bundle.js:7
t.loadTemplate @ vendor-bundle.js:7
fetch @ vendor-bundle.js:7
load @ vendor-bundle.js:7
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
u @ vendor-bundle.js:2
callPlugin @ vendor-bundle.js:3
fetch @ vendor-bundle.js:2
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
each @ vendor-bundle.js:2
emit @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
callPlugin @ vendor-bundle.js:3
fetch @ vendor-bundle.js:2
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
each @ vendor-bundle.js:2
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u._import @ vendor-bundle.js:7
e.loadTemplate @ vendor-bundle.js:7
M @ vendor-bundle.js:10
t.loadViewFactory @ vendor-bundle.js:11
t.loadViewFactory @ vendor-bundle.js:10
t.load @ vendor-bundle.js:11
(anonymous) @ vendor-bundle.js:12
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
t.importViewModelResource @ vendor-bundle.js:11
t.ensureViewModel @ vendor-bundle.js:12
t.createController @ vendor-bundle.js:12
t._createControllerAndSwap @ vendor-bundle.js:12
t.compose @ vendor-bundle.js:12
t.compose @ vendor-bundle.js:12
t.setRoot @ vendor-bundle.js:6
(anonymous) @ app-bundle.js:1
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
a._resolve @ vendor-bundle.js:2
a._promiseFulfilled @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
a._resolve @ vendor-bundle.js:2
a._promiseFulfilled @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
e.loadAllModules @ vendor-bundle.js:7
t.importViewResources @ vendor-bundle.js:11
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
a._resolve @ vendor-bundle.js:2
a._promiseFulfilled @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
i @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
i @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
i @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
i @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
i @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
i @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
i._drainQueue @ vendor-bundle.js:1
i._drainQueues @ vendor-bundle.js:1
drainQueues @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
i._queueTick @ vendor-bundle.js:1
s @ vendor-bundle.js:1
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
each @ vendor-bundle.js:2
emit @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
f @ vendor-bundle.js:2
completeLoad @ vendor-bundle.js:3
onScriptLoad @ vendor-bundle.js:3
load (async)
req.load @ vendor-bundle.js:3
load @ vendor-bundle.js:3
load @ vendor-bundle.js:2
fetch @ vendor-bundle.js:2
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:2
each @ vendor-bundle.js:2
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
a @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromiseCtx @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
c.hasDevTools.i.invoke @ vendor-bundle.js:1
r._then @ vendor-bundle.js:2
r.then @ vendor-bundle.js:2
l @ vendor-bundle.js:6
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:1
Promise.then (async)
i @ vendor-bundle.js:2
c.hasDevTools.i.settlePromises @ vendor-bundle.js:1
r._fulfill @ vendor-bundle.js:2
r._resolveCallback @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:7
execCb @ vendor-bundle.js:3
check @ vendor-bundle.js:3
enable @ vendor-bundle.js:3
init @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:3
setTimeout (async)
req.nextTick @ vendor-bundle.js:3
o @ vendor-bundle.js:3
requirejs @ vendor-bundle.js:3
(anonymous) @ vendor-bundle.js:7
e._execute @ vendor-bundle.js:1
r._resolveFromExecutor @ vendor-bundle.js:2
r @ vendor-bundle.js:2
n.PLATFORM.global.System.n.PLATFORM.global.System.import.u.loadModule @ vendor-bundle.js:7
(anonymous) @ vendor-bundle.js:6
i @ vendor-bundle.js:2
r._settlePromiseFromHandler @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
r._fulfill @ vendor-bundle.js:2
a._resolve @ vendor-bundle.js:2
a._promiseFulfilled @ vendor-bundle.js:2
r._settlePromise @ vendor-bundle.js:2
r._settlePromise0 @ vendor-bundle.js:2
r._settlePromises @ vendor-bundle.js:2
(anonymous) @ vendor-bundle.js:1
```
