### ISSUE TITLE
Can't start the app

### ISSUE THREAD

**Issue by ilhamwahabi** [urbanriskmap/cognicity-cards#48]
cognicity-cards $ au -v
0.35.1
cognicity-cards $ npm -v
6.4.1 ```(am i must using version 3.x ?)```
cognicity-cards $ node -v
v8.10.0

Tested in: Ubuntu 18.04 and Windows 8.1 64 bit

I am even not edit any code, just doing npm install and start it. But not worked.
Is this related? https://github.com/aurelia/cli/issues/924

```sh
GX (master *) cognicity-cards $ DEP=pb npm start

> cognicity-cards@1.1.0 start E:\aurelia\aw\cognicity-cards
> rm -rf src/routes/_route_handlers/* && au run --env dev --dep $DEP --watch

E:\aurelia\aw\cognicity-cards\node_modules\async-done\index.js:18
    throw err;
    ^

Error: Unhandled "error" event. ([object Object])
    at Gulp.emit (events.js:186:19)
    at Object.error (E:\aurelia\aw\cognicity-cards\node_modules\undertaker\lib\helpers\createExtensions.js:61:10)
    at handler (E:\aurelia\aw\cognicity-cards\node_modules\now-and-later\lib\mapSeries.js:43:14)
    at f (E:\aurelia\aw\cognicity-cards\node_modules\once\once.js:25:25)
    at f (E:\aurelia\aw\cognicity-cards\node_modules\once\once.js:25:25)
    at tryCatch (E:\aurelia\aw\cognicity-cards\node_modules\async-done\index.js:24:15)
    at done (E:\aurelia\aw\cognicity-cards\node_modules\async-done\index.js:40:12)
    at Domain.onError (E:\aurelia\aw\cognicity-cards\node_modules\async-done\index.js:51:5)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cognicity-cards@1.1.0 start: `rm -rf src/routes/_route_handlers/* && au run --env dev --dep $DEP --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cognicity-cards@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GX\AppData\Roaming\npm-cache\_logs\2018-11-09T07_05_27_819Z-debug.log
```

**Comment by matthewberryman** [comment]
I can't reproduce (tested in macOS 10.14.2 beta and Ubuntu 18.04)—I am using node v11 (under macOS) and v10 (under Ubuntu), with corresponding npm. Your setup looks odd to me- are you using Windows Subsystem for Linux (WSL)? Maybe aurelia is having trouble finding a file in that environment?
